### ISSUE TITLE
Cannot import 'NetworkXLabelGraphClusterer'

### ISSUE THREAD

**Issue by ghiandonigianmarco** [scikit-multilearn/scikit-multilearn#154]
I am just trying to import NetworkXLabelGraphClusterer using scikit-multilearn==0.2.0 but I get this error as it is not in the package: "cannot import name 'NetworkXLabelGraphClusterer'"

I am just running the code you provide in "5.2.2. Estimating hyper-parameter k for embedded classifiers"

Best,

Giammy

**Comment by wizardwangbin** [comment]
I just meet the same problem. The error message is as follow.

from skmultilearn.cluster import NetworkXLabelGraphClusterer
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-1041a51780b1>", line 1, in <module>
    from skmultilearn.cluster import NetworkXLabelGraphClusterer
ImportError: cannot import name 'NetworkXLabelGraphClusterer'

**Comment by oguerrer** [comment]
Hello,

I am having the same issue with `from skmultilearn.cluster import NetworkXLabelGraphClusterer`

It also comes up with 
`IGraphLabelGraphClusterer`, `GraphToolLabelGraphClusterer` and `StochasticBlockModel`

I tried the suggestion of using `from skmultilearn.cluster.networkx import NetworkXLabelGraphClusterer` but I get: `ModuleNotFoundError: No module named 'community'`

I have tried with versions 0.2.0 and 0.1.0 of scikit-multilearn. Any idea why this is happening?

Thanks

**Comment by wizardwangbin** [comment]
> Hello,
> 
> I am having the same issue with `from skmultilearn.cluster import NetworkXLabelGraphClusterer`
> 
> It also comes up with
> `IGraphLabelGraphClusterer`, `GraphToolLabelGraphClusterer` and `StochasticBlockModel`
> 
> I tried the suggestion of using `from skmultilearn.cluster.networkx import NetworkXLabelGraphClusterer` but I get: `ModuleNotFoundError: No module named 'community'`
> 
> I have tried with versions 0.2.0 and 0.1.0 of scikit-multilearn. Any idea why this is happening?
> 
> Thanks

You need to install the community package.  Download https://github.com/taynaud/python-louvain and install.

**Comment by oguerrer** [comment]
Thanks! This solves the issue.
