### ISSUE TITLE
No module named 'graph_tool'

### ISSUE THREAD

**Issue by chenkejin** [scikit-multilearn/scikit-multilearn#191]
Using graphtool package,the error occurs as follows:
from skmultilearn.cluster.graphtool import GraphToolLabelGraphClusterer, StochasticBlockModel
Traceback (most recent call last):
  File "skmultilearn_model.py", line 15, in <module>
    from skmultilearn.cluster.graphtool import GraphToolLabelGraphClusterer, StochasticBlockModel
  File "/home/chenkejin/anaconda3/lib/python3.6/site-packages/skmultilearn/cluster/graphtool.py", line 4, in <module>
    import graph_tool.all as gt
ModuleNotFoundError: No module named 'graph_tool'

**Comment by VeeruGandhad** [comment]
Did you get a solution for the issue ?

**Comment by chenkejin** [comment]
> Did you get a solution for the issue ?

not yet

**Comment by johncliu** [comment]
Install the graph-tool package first (see https://git.skewed.de/count0/graph-tool/-/wikis/installation-instructions)
