### ISSUE TITLE
ImportError: No module named 'sphinx_pypi_upload' on installing from github

### ISSUE THREAD

**Issue by queirozfcom** [scikit-multilearn/scikit-multilearn#28]
Hi. I've tried to install scikit-multilearn directly from github like this, and got this error:

```
(venv3)felipe@felipe-XPS-8300:~/auto-tagger$ pip install git+https://github.com/queirozfcom/scikit-multilearn.git
Collecting git+https://github.com/queirozfcom/scikit-multilearn.git
  Cloning https://github.com/queirozfcom/scikit-multilearn.git to /tmp/pip-agw71wfn-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-agw71wfn-build/setup.py", line 3, in <module>
        import sphinx_pypi_upload
    ImportError: No module named 'sphinx_pypi_upload'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-agw71wfn-build
```

Any thoughts? By the way, I'm using Python 3. Should I use Python 2?

**Comment by niedakh** [comment]
The master branch is installable using pip - I removed the dependency on sphinx_pypi_upload as it is just used for generating documentation upon releasing releasing.

I am using Python 2, I would plan for Python 3 in release 0.0.3, I want 0.0.2 out ASAP but still need to clean up some code.
