### ISSUE TITLE
fix a problem with predict_proba in BR

### ISSUE THREAD

**Issue by niedakh** [scikit-multilearn/scikit-multilearn#53]
crashes when testing on some data sets, ex. genbase

**Comment by 123banana** [comment]
I have meet a problem when i use predict_proba:
--------------------code-----------------
base_classifier= LogisticRegression(C=0.01,class_weight='balanced')
problem_transform_classifier = LabelPowerset(classifier=base_classifier,
    require_dense=[False, False])
clusterer = IGraphLabelCooccurenceClusterer('fastgreedy', weighted=True,
    include_self_edges=True)
classifier = LabelSpacePartitioningClassifier(problem_transform_classifier, clusterer)
classifier.fit(s1_fmri_delay6_train,stimuli_delay6_train)
test_label_proba=classifier.predict_proba(s1_fmri_delay6_test)
-------------------------error----------------------
Traceback (most recent call last):

  File "<ipython-input-22-986e738af005>", line 1, in <module>
    test_label_proba=classifier.predict_proba(s1_fmri_delay6_test)
  File "/home/banana/anaconda2/lib/python2.7/site-packages/skmultilearn/problem_transform/br.py", line 108, in predict_proba
    self.ensure_input_format(X)))[:, 1] for label in range(self.model_count)]
  File "/home/banana/anaconda2/lib/python2.7/site-packages/scipy/sparse/lil.py", line 274, in __getitem__
    j = self._check_col_bounds(j)
  File "/home/banana/anaconda2/lib/python2.7/site-packages/scipy/sparse/lil.py", line 237, in _check_col_bounds
    raise IndexError('column index out of bounds')
IndexError: column index out of bounds
-------------------------------------
can anyone tell me what's wrong?
thank you!

**Comment by 102206502** [comment]
It seems like I meet similar problem.

`
classifier = BinaryRelevance(GaussianNB())
classifier.fit(X_train, y_train)
predictions = classifier.predict_proba(X_test.tocoo())
`
X_train is sparse matrix of tfidf
y_train is ndarray
It crash when I have 50 labels, but not in 4 or 21 labels

**Traceback (most recent call last):
  File "E:\KnowledgePointClassifier\main.py", line 100, in <module>
    test.main()
  File "E:\KnowledgePointClassifier\main.py", line 39, in main
    self.evaluate_topK_in_layers(X_train, X_test, Y_train, Y_test, classifier)
  File "E:\KnowledgePointClassifier\main.py", line 61, in evaluate_topK_in_layers
    predictions = classifier.predict_proba(X_test.tocoo())
  File "C:\Anaconda2\lib\site-packages\skmultilearn\problem_transform\br.py", line 108, in predict_proba
    self.ensure_input_format(X)))[:, 1] for label in range(self.model_count)]
  File "C:\Anaconda2\lib\site-packages\scipy\sparse\csr.py", line 304, in __getitem__
    return self._get_submatrix(row, col)
  File "C:\Anaconda2\lib\site-packages\scipy\sparse\csr.py", line 456, in _get_submatrix
    j0, j1 = process_slice(col_slice, N)
  File "C:\Anaconda2\lib\site-packages\scipy\sparse\csr.py", line 451, in process_slice
    " %d <= %d" % (i0, num, i1, num, i0, i1))
IndexError: index out of bounds: 0 <= 1 <= 1, 0 <= 2 <= 1, 1 <= 2**

Is that cause by the bug of predict_proba?

**Comment by YEslahi** [comment]
I still have this bug. scikit-multilearn version 0.2.0 and python 3.7. 

In some runs, it doesn't appear and in others, it appears. My code:


       classifier = BinaryRelevance(
            classifier = RandomForestClassifier(n_estimators = 10)
        )
        
        X_train_numpyarray = array(X_train)
        X_test_numpyarray = array(X_test)

        classifier.fit(X_train_numpyarray, Y_train)

        confidence_cl = classifier.predict_proba(X_test_numpyarray)
        print("classifier.predict_proba", confidence_cl)

What other info you need ? 

Thanks.

**Comment by diegofg93** [comment]
I think the problem is because a minority class doesn't predict any labels and leaves the column out. I haven't reviewed the code much in scipy but increasing the dataset with more tags solved the error.
